import sys
import os
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

# Append the root directory to the system path. 
# This allows Python to locate and import modules from the main project folder.
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

import config
from sessions import create_spark_session
from hourly_transformation import calculate_hourly_indicators

def run_gold_hourly_pipeline():
    # Initialize the Spark Session for the Hourly Gold pipeline and retrieve the Spark Context
    spark = create_spark_session(app_name="SP500_Gold_Hourly")
    sc = spark.sparkContext
    
    print(" Reading cleaned data from Silver Layer...")
    # Read all cleaned parquet files from the Silver layer.
    # Spark automatically reads and merges all files within the specified directory into a single DataFrame.
    df = spark.read.parquet(config.SILVER_HOURLY_PATH)
    
    print(" Applying Gold Layer transformations (Indicators & GICS Sector)...")
    # Apply business logic, calculating hourly financial indicators and mapping the GICS sector
    gold_df = calculate_hourly_indicators(df)
    
    # Select only the necessary columns to ensure the final output schema remains clean and structured
    final_df = gold_df.select(
        "Date", "Ticker", "GICS_Sector", "Close", 
        "Hourly_Return", "SMA_Short", "SMA_Long", "RSI", "MACD_Line"
    )
    
    # Extract a list of all unique company tickers present in the transformed dataset
    tickers = [row['Ticker'] for row in final_df.select("Ticker").distinct().collect()]
    print(f" Saving {len(tickers)} companies to Gold Layer individually...")
    
    # Loop through each ticker to save its data as a standalone file
    for ticker in tickers:
        if not ticker:
            continue
            
        # Filter the dataframe to isolate data for the current ticker
        ticker_df = final_df.filter(F.col("Ticker") == ticker)
        
        # Define temporary and final storage paths
        temp_dir = config.GOLD_HOURLY_PATH + f"temp_{ticker}"
        final_file = config.GOLD_HOURLY_PATH + f"{ticker}.parquet"
        
        # Use coalesce(1) to force Spark to write all data for this ticker into a single file part inside the temporary folder
        ticker_df.coalesce(1).write.mode("overwrite").parquet(temp_dir)
        
        # Access the Hadoop FileSystem API to perform low-level file manipulations
        Path = sc._jvm.org.apache.hadoop.fs.Path
        temp_dir_path = Path(temp_dir)
        fs = temp_dir_path.getFileSystem(sc._jsc.hadoopConfiguration())
        
        # Search for the actual .parquet file generated by Spark inside the temporary folder
        temp_files = fs.globStatus(Path(temp_dir + "/part-*.parquet"))
        
        if temp_files:
            src_path = temp_files[0].getPath()
            dst_path = Path(final_file)
            
            # If a final file for this ticker already exists, delete it to prevent conflicts
            if fs.exists(dst_path):
                fs.delete(dst_path, False)
                
            # Rename and move the generated file from the temporary folder to its exact final name
            fs.rename(src_path, dst_path)
            
        # Delete the now-empty temporary directory to keep the storage bucket clean
        fs.delete(temp_dir_path, True)
        print(f" Gold File Saved: {ticker}.parquet")

    print(" Gold Hourly Pipeline completed successfully with exact file names!")
    spark.stop()

if __name__ == "__main__":
    run_gold_hourly_pipeline()