#run_gold_daily_pipeline
import sys
import os
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

# Append the root directory to the system path. 
# This allows Python to locate and import modules (like config and sessions) from the main project folder.
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

import config
from sessions import create_spark_session
from daily_transformation import calculate_daily_indicators 

def run_gold_daily_pipeline():
    # Initialize the Spark Session for the Daily Gold pipeline
    spark = create_spark_session(app_name="SP500_Gold_Daily")
    sc = spark.sparkContext
    
    print(" Reading cleaned data from Silver Layer (Daily)...")
    # Read the cleaned parquet files from the Silver layer
    df = spark.read.parquet(config.SILVER_DAILY_PATH)
    
    print(" Applying Gold Layer transformations (Daily Indicators & GICS Sector)...")
    # Apply business logic, financial indicators, and sector mapping
    gold_df = calculate_daily_indicators(df)
    
    # Select only the necessary columns to keep the final output clean and structured
    final_df = gold_df.select(
        "Date", "Ticker", "GICS_Sector", "Close", 
        "Daily_Return", "Rolling_30Day_StdDev", 
        "SMA_50", "SMA_200", "Signal",          
        "RSI", "MACD_Line", "MACD_Signal_Line"  
    )
    
    # Extract a list of all unique company tickers present in the dataframe
    tickers = [row['Ticker'] for row in final_df.select("Ticker").distinct().collect()]
    print(f" Saving {len(tickers)} companies to Gold Layer individually...")
    
    # Loop through each ticker to save its data in a separate file
    for ticker in tickers:
        if not ticker:
            continue
            
        # Filter the dataframe to only include data for the current ticker
        ticker_df = final_df.filter(F.col("Ticker") == ticker)
        
        # Define temporary and final paths
        # Spark naturally saves data as a folder of parts. We use a temp folder first.
        temp_dir = config.GOLD_DAILY_PATH + f"temp_{ticker}"
        final_file = config.GOLD_DAILY_PATH + f"{ticker}.parquet"
        
        # coalesce(1) forces Spark to combine all data for this ticker into a single file part inside the temp folder
        ticker_df.coalesce(1).write.mode("overwrite").parquet(temp_dir)
        
        # Setup Hadoop FileSystem (FS) to manage files directly
        Path = sc._jvm.org.apache.hadoop.fs.Path
        temp_dir_path = Path(temp_dir)
        fs = temp_dir_path.getFileSystem(sc._jsc.hadoopConfiguration())
        
        # Search for the actual .parquet file generated by Spark inside the temp folder
        temp_files = fs.globStatus(Path(temp_dir + "/part-*.parquet"))
        
        if temp_files:
            src_path = temp_files[0].getPath()
            dst_path = Path(final_file)
            
            # If a file with this ticker name already exists in the Gold layer, delete it to avoid conflicts
            if fs.exists(dst_path):
                fs.delete(dst_path, False)
                
            # Rename and move the single part file out of the temp folder to the final destination
            fs.rename(src_path, dst_path)
            
        # Delete the now-empty temporary folder
        fs.delete(temp_dir_path, True)
        print(f" Gold Daily File Saved: {ticker}.parquet")

    print(f" Gold Daily Pipeline completed successfully! Created {len(tickers)} files.")
    spark.stop()

if __name__ == "__main__":
    run_gold_daily_pipeline()